on:
  push:
  workflow_dispatch:


jobs:

  build:
    strategy:
      matrix:
        arch: [x86, x64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: fu1ny2t-3es/pr1je2to3ra4s@build
      with:
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}
